version: "3.7"

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  docker-test-dev:
    image: ehyeok9/docker-test-dev
    ports:
      - "8080:8080"
    environment:
      SERVER_MODE: prod
      TZ: "Asia/Seoul"
    depends_on:
      - redis