spring:

  profiles:
    include: oauth

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:routine-up;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret: ${JWT_SECRET}
  expiration_in_ms: ${JWT_EXPIRATION_IN_MS}

logging:
  level:
    "[km.cd.backend]": debug